<?php

/**
 * @file
 * Contains modules hook.
 */

/**
 * Implements hook_library_info_alter().
 */
function kaizen_library_info_alter(array &$libraries, $extension) {
  /** @var \Drupal\kaizen\KaizenManager $manager */
  $manager = \Drupal::service('kaizen.manager');

  $definitions = $manager->getDefinitions();

  foreach ($definitions as $definition) {

    if ($definition['provider'] != $extension) {
      continue;
    }
    if (isset($definition['library'])) {
      $library = $definition['library'];

      $relative_path_to_component = str_replace($definition['provider_path'] . '/', "", $definition['component_path']);

      if (isset($library['css'])) {
        foreach ($library['css'] as $category_name => $category) {
          foreach ($category as $file_path => $file) {
            unset($libraries[$definition['id']]['css'][$category_name][$file_path]);
            $file_path = str_replace('COMPONENT', $relative_path_to_component, $file_path);
            $libraries[$definition['id']]['css'][$category_name][$file_path] = $file;
          }
        }
      }
      if (isset($library['js'])) {
        foreach ($library['js'] as $file_path => $file) {
          unset($libraries[$definition['id']]['js'][$file_path]);
          $file_path = str_replace('COMPONENT', $relative_path_to_component, $file_path);
          $libraries[$definition['id']]['js'][$file_path] = $file;
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function kaizen_theme($existing, $type, $theme, $path) {
  /** @var \Drupal\kaizen\KaizenManager $manager */
  $manager = \Drupal::service('kaizen.manager');

  $definitions = $manager->getDefinitions();
  $templates = [];

  foreach ($definitions as $definition) {
    // Cut .html.twig file extensiions.
    $templates['kaizen_' . $definition['id']] = [
      'template' => $definition['plugins']['formatter']['template'],
      'theme path' => $definition['provider_path'],
      'path' => $definition['component_path'],
      'variables' => [
        'attributes' => NULL,
        'content' => NULL,
      ],
    ];
  }

  return $templates;
}
